module.exports = {
  extends: ['@commitlint/config-angular'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'chore',
        'docs',
        'style',
        'test',
        'ci',
        'release',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'other',
        'app',
        'pnpm',
        'core',
        'user-service',
        'transformers',
        'guard',
        'decorator',
        'utils',
        'cache',
        'database',
        'helper',
        'auth',
        'config',
      ],
    ],
  },
};
